[[main]]
name = "Home"
url = "/"
weight = 10

[[main]]
name = "Research"
pageRef = "research"
weight = 20

[[main]]
name = "Projects"
pageRef = "projects"
weight = 30

[[main]]
name = "Writing"
pageRef = "writing"
weight = 40

[[main]]
name = "About"
pageRef = "about"
weight = 50

[[main]]
name = "Contact"
pageRef = "contact"
weight = 60
